<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Wipe existing products and pivot
        \DB::table('category_product')->delete();
        Product::query()->delete();

        $cats = Category::pluck('id', 'name');

        $products = [

            // ── Electronics (15) ──────────────────────────────────────────
            ['name'=>'4K Smart LED TV 55"',          'desc'=>'Ultra HD 4K smart TV with HDR10+, Dolby Vision and built-in Wi-Fi. Perfect for an immersive home cinema.',                                     'price'=>89999,  'qty'=>25, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600'],
            ['name'=>'Wireless Mechanical Keyboard',  'desc'=>'TKL compact mechanical keyboard with RGB backlight, blue switches and 2.4GHz wireless connection.',                                            'price'=>8499,   'qty'=>60, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600'],
            ['name'=>'Ergonomic Gaming Mouse',        'desc'=>'12000 DPI optical sensor, 7 programmable buttons, RGB lighting and ambidextrous design for all-day comfort.',                                  'price'=>3999,   'qty'=>80, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600'],
            ['name'=>'USB-C 65W Fast Charger',        'desc'=>'GaN technology charger supports PD 3.0 fast charging for laptops, tablets and smartphones. Compact foldable plug.',                            'price'=>2199,   'qty'=>120,'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1615526675146-cb0e1b2a6b8e?w=600'],
            ['name'=>'Portable Power Bank 20000mAh',  'desc'=>'Slim dual-port power bank with 22.5W fast charge output, LED indicator and premium lithium polymer cells.',                                    'price'=>4799,   'qty'=>90, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600'],
            ['name'=>'Smart Home Hub',                'desc'=>'Central control for all your smart devices. Compatible with Alexa, Google Home and Apple HomeKit.',                                            'price'=>12999,  'qty'=>35, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
            ['name'=>'Webcam 1080p HD',               'desc'=>'Full HD webcam with autofocus, built-in dual microphone and privacy shutter. Great for video calls and streaming.',                            'price'=>5499,   'qty'=>55, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=600'],
            ['name'=>'External SSD 1TB',              'desc'=>'Ultra-fast NVMe external SSD with USB 3.2 Gen 2 speeds up to 1050MB/s. Shock resistant and pocket-sized.',                                    'price'=>14999,  'qty'=>40, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600'],
            ['name'=>'Wireless Charging Pad',         'desc'=>'15W Qi wireless charging pad compatible with all Qi-enabled devices. Non-slip surface with foreign object detection.',                         'price'=>1899,   'qty'=>100,'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600'],
            ['name'=>'Smart LED Strip Lights 5m',     'desc'=>'RGB+W LED strip with app control, voice assistant support, music sync mode and adhesive backing.',                                             'price'=>2499,   'qty'=>75, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=600'],
            ['name'=>'Digital Drawing Tablet',        'desc'=>'8192 levels of pressure sensitivity, tilt recognition, battery-free stylus. Compatible with Windows and macOS.',                               'price'=>18999,  'qty'=>22, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600'],
            ['name'=>'Portable Projector Mini',       'desc'=>'1080p native resolution, 200 ANSI lumens, built-in speaker and Android OS. Projects up to 120" screen.',                                      'price'=>34999,  'qty'=>15, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600'],
            ['name'=>'Bluetooth Speaker Waterproof',  'desc'=>'IPX7 waterproof, 360° sound, 24-hour battery life and hands-free calling. Perfect for outdoor adventures.',                                    'price'=>6799,   'qty'=>65, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600'],
            ['name'=>'Action Camera 4K',              'desc'=>'4K/60fps video, 20MP photos, EIS stabilization, waterproof to 10m without housing. Includes mounting accessories.',                            'price'=>29999,  'qty'=>18, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600'],
            ['name'=>'Smart Doorbell Camera',         'desc'=>'1080p HD video doorbell with motion detection, two-way audio, night vision and cloud storage.',                                                'price'=>9999,   'qty'=>30, 'cat'=>'Electronics',          'img'=>'https://images.unsplash.com/photo-1558002038-1055907df827?w=600'],

            // ── Smartphones (10) ──────────────────────────────────────────
            ['name'=>'Flagship Smartphone Pro Max',   'desc'=>'6.7" AMOLED 120Hz display, 200MP triple camera, 5000mAh battery with 65W charging, 12GB RAM + 256GB storage.',                              'price'=>159999, 'qty'=>20, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600'],
            ['name'=>'Budget 5G Smartphone',          'desc'=>'5G capable phone with 6.5" LCD, 50MP camera, 5000mAh battery and 4GB RAM. Great value for money.',                                           'price'=>28999,  'qty'=>45, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600'],
            ['name'=>'Foldable Smartphone',           'desc'=>'Innovative foldable design with 7.6" inner display, Snapdragon 8 Gen 2, 12GB RAM and IPX8 water resistance.',                                'price'=>299999, 'qty'=>8,  'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600'],
            ['name'=>'Smartphone Rugged Edition',     'desc'=>'Military-grade durability, IP68 rated, 6000mAh battery, thermal camera and walkie-talkie mode. For extreme environments.',                    'price'=>49999,  'qty'=>25, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600'],
            ['name'=>'Slim Flagship Smartphone',      'desc'=>'World\'s thinnest smartphone at 5.9mm, 6.1" OLED, 50MP camera system and 30W wireless charging.',                                            'price'=>89999,  'qty'=>30, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600'],
            ['name'=>'Gaming Smartphone 165Hz',       'desc'=>'165Hz AMOLED display, Snapdragon 8 Gen 3, 18GB RAM, 6000mAh + 120W charging and shoulder trigger buttons.',                                  'price'=>119999, 'qty'=>15, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1617897903246-719242758050?w=600'],
            ['name'=>'Smartphone Camera Edition',     'desc'=>'Periscope zoom camera with 10x optical zoom, Hasselblad tuning, 1-inch sensor and professional video modes.',                                 'price'=>139999, 'qty'=>12, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600'],
            ['name'=>'Entry-Level Android Phone',     'desc'=>'Reliable daily driver with 6.5" IPS display, 13MP camera, 4GB RAM, 64GB storage and 4500mAh battery.',                                       'price'=>15999,  'qty'=>70, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600'],
            ['name'=>'Smartphone with Stylus',        'desc'=>'S Pen included, 6.8" QHD+ display, DeX desktop mode, 45W fast charging and 10x optical zoom camera.',                                        'price'=>179999, 'qty'=>10, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=600'],
            ['name'=>'Compact Smartphone 5.4"',       'desc'=>'One-handed use design, 5.4" Super Retina XDR display, A15 Bionic chip, 12MP dual camera and all-day battery.',                               'price'=>79999,  'qty'=>35, 'cat'=>'Smartphones',          'img'=>'https://images.unsplash.com/photo-1601972599748-39571d75e2f2?w=600'],

            // ── Laptops & Computers (10) ──────────────────────────────────
            ['name'=>'Ultrabook 14" Core i7',         'desc'=>'Intel Core i7-13th gen, 16GB LPDDR5, 512GB NVMe SSD, 14" IPS FHD display, 12-hour battery and backlit keyboard.',                           'price'=>149999, 'qty'=>18, 'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600'],
            ['name'=>'Gaming Laptop RTX 4060',        'desc'=>'RTX 4060, Intel i9-13900H, 32GB DDR5, 1TB SSD, 15.6" 144Hz IPS, per-key RGB keyboard and advanced cooling.',                                 'price'=>249999, 'qty'=>10, 'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600'],
            ['name'=>'MacBook-Style Slim Laptop',     'desc'=>'M2-class processor, 13.3" Retina display, 8GB unified memory, 256GB SSD, Touch ID and MagSafe charging.',                                    'price'=>199999, 'qty'=>12, 'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600'],
            ['name'=>'2-in-1 Convertible Laptop',     'desc'=>'360° hinge touchscreen laptop with 12th gen Intel, 16GB RAM, 512GB SSD, stylus support and 13" FHD+ display.',                               'price'=>129999, 'qty'=>20, 'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600'],
            ['name'=>'Desktop PC Gaming Tower',       'desc'=>'RTX 4070, Intel i7-13700K, 32GB DDR5, 2TB SSD, 850W PSU, tempered glass case with ARGB fans.',                                               'price'=>349999, 'qty'=>7,  'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600'],
            ['name'=>'Mini PC Compact Desktop',       'desc'=>'Intel NUC-style mini PC with Core i5, 16GB RAM, 512GB SSD, 4K output, Wi-Fi 6 and Bluetooth 5.2.',                                           'price'=>69999,  'qty'=>25, 'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1593640408182-31c228ef56f2?w=600'],
            ['name'=>'Budget Laptop for Students',    'desc'=>'14" HD display, Intel Celeron N4020, 8GB RAM, 256GB SSD, Windows 11 Home and 6-hour battery life.',                                           'price'=>39999,  'qty'=>40, 'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600'],
            ['name'=>'Chromebook Education',          'desc'=>'13.3" FHD display, MediaTek Kompanio 520, 4GB RAM, 64GB eMMC, Chrome OS, MIL-SPEC drop tested.',                                              'price'=>29999,  'qty'=>35, 'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=600'],
            ['name'=>'27" 4K Monitor IPS',            'desc'=>'27-inch 4K IPS monitor with HDR400, 99% sRGB, USB-C 65W charging, built-in speakers and height adjustable stand.',                            'price'=>79999,  'qty'=>20, 'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600'],
            ['name'=>'Workstation Laptop 17"',        'desc'=>'Xeon/ECC RAM workstation laptop for professionals — 17" UHD display, NVIDIA Quadro, 64GB RAM, 2TB SSD.',                                      'price'=>499999, 'qty'=>5,  'cat'=>'Laptops & Computers',  'img'=>'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600'],

            // ── Audio & Headphones (8) ────────────────────────────────────
            ['name'=>'Noise Cancelling Headphones',   'desc'=>'40dB ANC, 30-hour battery, Hi-Res Audio, foldable design and premium memory foam ear cushions.',                                              'price'=>19999,  'qty'=>50, 'cat'=>'Audio & Headphones',   'img'=>'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600'],
            ['name'=>'True Wireless Earbuds Pro',     'desc'=>'Active noise cancellation, 8h battery + 24h case, IPX4, custom EQ app and multipoint Bluetooth connection.',                                  'price'=>12999,  'qty'=>70, 'cat'=>'Audio & Headphones',   'img'=>'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600'],
            ['name'=>'Studio Monitor Headphones',     'desc'=>'Open-back reference headphones with 40mm dynamic drivers, detachable cable and velour ear pads for professional mixing.',                      'price'=>24999,  'qty'=>30, 'cat'=>'Audio & Headphones',   'img'=>'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600'],
            ['name'=>'Gaming Headset 7.1 Surround',   'desc'=>'Virtual 7.1 surround sound, detachable flip-up mic, 53mm drivers, soft leatherette cushions and USB audio.',                                  'price'=>7499,   'qty'=>55, 'cat'=>'Audio & Headphones',   'img'=>'https://images.unsplash.com/photo-1599669454699-248893623440?w=600'],
            ['name'=>'Soundbar 2.1 with Subwoofer',   'desc'=>'120W output, Dolby Atmos, HDMI ARC, Bluetooth 5.0, wall-mountable and wireless subwoofer included.',                                         'price'=>34999,  'qty'=>20, 'cat'=>'Audio & Headphones',   'img'=>'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600'],
            ['name'=>'Vinyl Record Player',           'desc'=>'Belt-drive turntable with built-in preamp, Bluetooth output, USB recording and adjustable counterweight.',                                     'price'=>16999,  'qty'=>15, 'cat'=>'Audio & Headphones',   'img'=>'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600'],
            ['name'=>'Budget Wired Earphones',        'desc'=>'In-ear earphones with 10mm dynamic drivers, tangle-free cable, inline mic and ergonomic fit for all ear sizes.',                              'price'=>799,    'qty'=>200,'cat'=>'Audio & Headphones',   'img'=>'https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=600'],
            ['name'=>'Portable DAC/Amp',              'desc'=>'Hi-Fi USB DAC + headphone amplifier, 32-bit/384kHz decoding, PCM & DSD support, compact enough for pocket use.',                             'price'=>9999,   'qty'=>25, 'cat'=>'Audio & Headphones',   'img'=>'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],

            // ── Clothing & Fashion (10) ───────────────────────────────────
            ['name'=>'Men\'s Classic Oxford Shirt',   'desc'=>'100% premium cotton Oxford fabric, button-down collar, single chest pocket, available in 12 colours and all sizes.',                          'price'=>2999,   'qty'=>150,'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600'],
            ['name'=>'Women\'s Floral Maxi Dress',    'desc'=>'Lightweight chiffon maxi dress with floral print, V-neckline, adjustable straps and side pockets.',                                           'price'=>3499,   'qty'=>100,'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600'],
            ['name'=>'Slim Fit Chino Trousers',       'desc'=>'Stretch cotton chinos in slim fit, flat front, available in 8 colours, machine washable and wrinkle resistant.',                              'price'=>2499,   'qty'=>120,'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600'],
            ['name'=>'Oversized Graphic Hoodie',      'desc'=>'380g heavyweight fleece hoodie, drop-shoulder fit, kangaroo pocket, ribbed cuffs. 100% organic cotton.',                                      'price'=>3999,   'qty'=>80, 'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600'],
            ['name'=>'Leather Jacket Men\'s',         'desc'=>'Genuine lambskin leather jacket, YKK zippers, quilted lining, slim fit biker style — a timeless wardrobe staple.',                           'price'=>18999,  'qty'=>30, 'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600'],
            ['name'=>'Women\'s Blazer Formal',        'desc'=>'Tailored women\'s blazer in ponte fabric, single-button closure, notched lapels and flap pockets. Office-ready.',                             'price'=>5999,   'qty'=>60, 'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600'],
            ['name'=>'Running Shorts Men\'s',         'desc'=>'Lightweight 4-way stretch running shorts with inner liner, zip pocket, reflective details and 7-inch inseam.',                                'price'=>1799,   'qty'=>200,'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1597852074816-d933c7d2b988?w=600'],
            ['name'=>'Denim Jeans Slim Tapered',      'desc'=>'Premium selvedge denim, slim tapered cut, slight stretch for comfort. Sanforized and pre-washed for the perfect fade.',                       'price'=>4499,   'qty'=>90, 'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600'],
            ['name'=>'Sports Bra High Support',       'desc'=>'High-impact sports bra with underwire-free support, moisture-wicking fabric, removable cups and racerback design.',                           'price'=>2299,   'qty'=>110,'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=600'],
            ['name'=>'Winter Puffer Jacket',          'desc'=>'600-fill power duck down, water-repellent DWR coating, packable into chest pocket, available in 6 colours.',                                  'price'=>9999,   'qty'=>45, 'cat'=>'Clothing & Fashion',   'img'=>'https://images.unsplash.com/photo-1604644401890-0bd678c83788?w=600'],

            // ── Books & Education (8) ─────────────────────────────────────
            ['name'=>'Clean Code by Robert Martin',   'desc'=>'The definitive guide to writing readable, maintainable and testable software. Essential for every professional developer.',                    'price'=>2999,   'qty'=>80, 'cat'=>'Books & Education',    'img'=>'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600'],
            ['name'=>'Atomic Habits by James Clear',  'desc'=>'Proven framework for building good habits and breaking bad ones. Over 10 million copies sold worldwide.',                                      'price'=>1999,   'qty'=>120,'cat'=>'Books & Education',    'img'=>'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600'],
            ['name'=>'Graphic Novel Collection Box',  'desc'=>'Collector\'s box set of 5 premium graphic novels with hardcover binding and full-colour artwork.',                                             'price'=>5999,   'qty'=>30, 'cat'=>'Books & Education',    'img'=>'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=600'],
            ['name'=>'IELTS Complete Preparation Kit','desc'=>'Official IELTS prep books + 6 practice tests, listening audio CDs and vocabulary flashcards. Score 7+ guaranteed.',                           'price'=>3499,   'qty'=>60, 'cat'=>'Books & Education',    'img'=>'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600'],
            ['name'=>'The Psychology of Money',       'desc'=>'Timeless lessons on wealth, greed and happiness. Morgan Housel\'s bestselling personal finance masterpiece.',                                 'price'=>1799,   'qty'=>100,'cat'=>'Books & Education',    'img'=>'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600'],
            ['name'=>'Drawing for Beginners',         'desc'=>'Step-by-step illustration guide covering sketching fundamentals, perspective, shading and composition.',                                       'price'=>1499,   'qty'=>55, 'cat'=>'Books & Education',    'img'=>'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600'],
            ['name'=>'Python Programming Cookbook',   'desc'=>'300+ practical Python recipes covering data science, web scraping, automation and machine learning.',                                          'price'=>3999,   'qty'=>45, 'cat'=>'Books & Education',    'img'=>'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600'],
            ['name'=>'Children\'s Encyclopaedia Set', 'desc'=>'12-volume hardback encyclopaedia for children aged 6-14. Vibrant illustrations, maps and fascinating facts.',                                 'price'=>7999,   'qty'=>20, 'cat'=>'Books & Education',    'img'=>'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600'],

            // ── Home & Kitchen (10) ───────────────────────────────────────
            ['name'=>'Air Fryer 5.5L Digital',        'desc'=>'1700W air fryer with 8 preset programs, digital display, non-stick basket and rapid air circulation for healthy cooking.',                    'price'=>12999,  'qty'=>40, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1648581553207-58d29ef6e5dc?w=600'],
            ['name'=>'Espresso Coffee Machine',       'desc'=>'15-bar pressure pump, 1.8L water tank, steam wand for frothing milk, programmable cup size and auto-shutoff.',                               'price'=>24999,  'qty'=>20, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600'],
            ['name'=>'Non-Stick Cookware Set 10pc',   'desc'=>'Granite-coated non-stick pans and pots with heat-resistant handles. Induction compatible, oven safe to 240°C.',                              'price'=>8999,   'qty'=>35, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600'],
            ['name'=>'Robot Vacuum Cleaner',          'desc'=>'3000Pa suction, LIDAR navigation, 180-min runtime, auto-empty base, mop function and zone-cleaning via app.',                                'price'=>49999,  'qty'=>15, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600'],
            ['name'=>'Stand Mixer 6.5Qt',             'desc'=>'800W planetary stand mixer with 6.5-quart bowl, 10 speeds, dough hook, whisk and flat beater attachments.',                                  'price'=>29999,  'qty'=>18, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=600'],
            ['name'=>'Bamboo Cutting Board Set',      'desc'=>'3-piece premium bamboo cutting board set with juice groove, non-slip feet and hanging holes. Eco-friendly and antibacterial.',                'price'=>2499,   'qty'=>90, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1566454419290-57a64afe35b7?w=600'],
            ['name'=>'Stainless Steel Water Bottle',  'desc'=>'Triple-insulated 1L bottle keeps drinks cold 24h / hot 12h. BPA-free, leak-proof lid and powder-coated exterior.',                           'price'=>1999,   'qty'=>150,'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600'],
            ['name'=>'Weighted Blanket 7kg',          'desc'=>'7kg glass bead weighted blanket for anxiety and better sleep. Breathable cotton shell with removable washable cover.',                        'price'=>7499,   'qty'=>30, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600'],
            ['name'=>'Smart Plugs Wi-Fi Pack of 4',   'desc'=>'Wi-Fi smart plugs with energy monitoring, voice assistant support, timer schedules and no hub required.',                                     'price'=>3999,   'qty'=>60, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
            ['name'=>'Aroma Diffuser + Essential Oil','desc'=>'300ml ultrasonic aroma diffuser with 7-colour LED, auto shutoff and 3 lavender essential oil bottles included.',                             'price'=>3499,   'qty'=>55, 'cat'=>'Home & Kitchen',       'img'=>'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600'],

            // ── Sports & Fitness (8) ──────────────────────────────────────
            ['name'=>'Adjustable Dumbbell Set 40kg',  'desc'=>'Dial-adjust dumbbells from 2.5kg to 20kg each. Space-saving design replaces 8 pairs of dumbbells. Tray included.',                           'price'=>24999,  'qty'=>20, 'cat'=>'Sports & Fitness',     'img'=>'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600'],
            ['name'=>'Yoga Mat Premium 6mm',          'desc'=>'Non-slip natural rubber yoga mat, 6mm thick, alignment lines, eco-friendly and odour resistant with carry strap.',                            'price'=>3499,   'qty'=>80, 'cat'=>'Sports & Fitness',     'img'=>'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=600'],
            ['name'=>'Smart Fitness Band',            'desc'=>'Track heart rate, SpO2, sleep, 100+ sports modes, 14-day battery and 1.47" AMOLED display. 5ATM water resistant.',                           'price'=>6999,   'qty'=>65, 'cat'=>'Sports & Fitness',     'img'=>'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600'],
            ['name'=>'Jump Rope Speed Cable',         'desc'=>'Bearing speed rope with adjustable 3m cable, aluminium handles and counter. Great for HIIT and boxing training.',                             'price'=>1299,   'qty'=>150,'cat'=>'Sports & Fitness',     'img'=>'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?w=600'],
            ['name'=>'Resistance Bands Set 5pc',      'desc'=>'5 resistance levels from 5-50lbs, latex-free, suitable for rehab, stretching and full-body workouts. Bag included.',                          'price'=>1799,   'qty'=>120,'cat'=>'Sports & Fitness',     'img'=>'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=600'],
            ['name'=>'Running Shoes Men\'s',          'desc'=>'Lightweight mesh upper, responsive EVA foam midsole, rubber outsole with multi-directional grip. Available in sizes 39-47.',                  'price'=>8999,   'qty'=>60, 'cat'=>'Sports & Fitness',     'img'=>'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600'],
            ['name'=>'Pull-Up Bar Doorframe',         'desc'=>'No-screw doorframe pull-up bar, supports up to 150kg, padded grips, also works as push-up and sit-up bar.',                                   'price'=>3999,   'qty'=>45, 'cat'=>'Sports & Fitness',     'img'=>'https://images.unsplash.com/photo-1571019613914-85f342c6a11e?w=600'],
            ['name'=>'Foam Roller Deep Tissue',       'desc'=>'High-density EVA foam roller for myofascial release, muscle recovery and flexibility. Grid-textured surface.',                                'price'=>2499,   'qty'=>70, 'cat'=>'Sports & Fitness',     'img'=>'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600'],

            // ── Beauty & Personal Care (8) ────────────────────────────────
            ['name'=>'Electric Face Cleanser',        'desc'=>'Sonic facial cleansing brush with 3 modes, waterproof, 4 interchangeable heads and 30-day battery per charge.',                               'price'=>5999,   'qty'=>40, 'cat'=>'Beauty & Personal Care','img'=>'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600'],
            ['name'=>'Hair Dryer 2200W Ionic',        'desc'=>'Professional ionic hair dryer, 2200W, 3 heat + 2 speed settings, cold shot button, diffuser and concentrator included.',                      'price'=>4999,   'qty'=>50, 'cat'=>'Beauty & Personal Care','img'=>'https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=600'],
            ['name'=>'Vitamin C Serum 30ml',          'desc'=>'20% Vitamin C + hyaluronic acid + niacinamide brightening serum. Fades dark spots, boosts collagen, fragrance-free.',                        'price'=>2499,   'qty'=>100,'cat'=>'Beauty & Personal Care','img'=>'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600'],
            ['name'=>'Men\'s Grooming Kit 7-in-1',    'desc'=>'All-in-one grooming set: hair clipper, beard trimmer, nose trimmer, ear trimmer, all with ceramic blades. USB rechargeable.',                 'price'=>3999,   'qty'=>60, 'cat'=>'Beauty & Personal Care','img'=>'https://images.unsplash.com/photo-1621607512022-6aecc4fed814?w=600'],
            ['name'=>'Electric Toothbrush Sonic',     'desc'=>'62000 strokes/min sonic toothbrush, 5 modes, smart timer, 3-month battery and pressure sensor. 4 brush heads included.',                     'price'=>6499,   'qty'=>45, 'cat'=>'Beauty & Personal Care','img'=>'https://images.unsplash.com/photo-1559591937-e0e2e6504e2d?w=600'],
            ['name'=>'Perfume Eau de Parfum 100ml',   'desc'=>'Long-lasting EDP with top notes of bergamot and citrus, heart of jasmine and oud base. 100ml spray bottle.',                                  'price'=>7999,   'qty'=>35, 'cat'=>'Beauty & Personal Care','img'=>'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600'],
            ['name'=>'Moisturiser SPF50 50ml',        'desc'=>'Lightweight daily moisturiser with SPF50, hyaluronic acid, ceramides and niacinamide. Non-greasy, suitable for all skin types.',               'price'=>1999,   'qty'=>120,'cat'=>'Beauty & Personal Care','img'=>'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600'],
            ['name'=>'Jade Roller & Gua Sha Set',     'desc'=>'100% natural jade facial roller with gua sha board. Reduces puffiness, improves circulation and enhances product absorption.',                 'price'=>1499,   'qty'=>80, 'cat'=>'Beauty & Personal Care','img'=>'https://images.unsplash.com/photo-1600428853876-fb12339f4b8e?w=600'],

            // ── Toys & Games (7) ──────────────────────────────────────────
            ['name'=>'LEGO Architecture Set 1500pcs', 'desc'=>'1500-piece LEGO set to build a detailed replica of a world-famous skyline. Ages 14+. Includes display stand.',                                'price'=>14999,  'qty'=>20, 'cat'=>'Toys & Games',         'img'=>'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600'],
            ['name'=>'Remote Control Monster Truck',  'desc'=>'1:10 scale RC monster truck, brushless motor, 4WD, 50km/h top speed, 2.4GHz controller and waterproof electronics.',                         'price'=>9999,   'qty'=>30, 'cat'=>'Toys & Games',         'img'=>'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600'],
            ['name'=>'Board Game Strategy Collection','desc'=>'Set of 5 award-winning strategy board games for family game night. Ages 8+, 2-6 players each. Premium components.',                           'price'=>5999,   'qty'=>25, 'cat'=>'Toys & Games',         'img'=>'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600'],
            ['name'=>'Kids Art & Craft Mega Kit',     'desc'=>'200-piece art kit with watercolours, acrylic paints, brushes, canvases, clay and activity guide for kids aged 5-12.',                         'price'=>3499,   'qty'=>50, 'cat'=>'Toys & Games',         'img'=>'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600'],
            ['name'=>'Wooden Train Set 60pcs',        'desc'=>'60-piece wooden train set with track, locomotives, cargo cars, bridges and buildings. Safe, non-toxic paint. Ages 3+.',                       'price'=>4999,   'qty'=>35, 'cat'=>'Toys & Games',         'img'=>'https://images.unsplash.com/photo-1558679908-541bcf1249ff?w=600'],
            ['name'=>'Playing Cards Premium Set',     'desc'=>'4-deck luxury playing cards in magnetic box. Air-cushion finish, casino-grade paper stock and smooth dealing.',                               'price'=>1499,   'qty'=>100,'cat'=>'Toys & Games',         'img'=>'https://images.unsplash.com/photo-1528819622765-d6bcf132f793?w=600'],
            ['name'=>'Chess Set Walnut & Maple',      'desc'=>'Tournament-size chess set with weighted Staunton pieces, walnut/maple board, felt base and storage bag.',                                      'price'=>6999,   'qty'=>18, 'cat'=>'Toys & Games',         'img'=>'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=600'],

            // ── Watches & Accessories (8) ─────────────────────────────────
            ['name'=>'Smart Watch AMOLED GPS',        'desc'=>'1.43" AMOLED, built-in GPS, SpO2, ECG, 14-day battery, 100+ workout modes and 5ATM water resistance.',                                       'price'=>29999,  'qty'=>30, 'cat'=>'Watches & Accessories', 'img'=>'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600'],
            ['name'=>'Minimalist Analog Watch Men\'s','desc'=>'40mm stainless steel case, sapphire crystal glass, Japanese quartz movement and genuine leather strap.',                                      'price'=>14999,  'qty'=>25, 'cat'=>'Watches & Accessories', 'img'=>'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600'],
            ['name'=>'Leather Wallet RFID Blocking',  'desc'=>'Slim bifold wallet in full-grain leather, RFID blocking, 6 card slots, 2 cash compartments. Slim profile.',                                   'price'=>2999,   'qty'=>80, 'cat'=>'Watches & Accessories', 'img'=>'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600'],
            ['name'=>'Sunglasses Polarised UV400',    'desc'=>'Aviator-style polarised sunglasses with UV400 protection, stainless steel frame and spring hinges. Case included.',                            'price'=>3499,   'qty'=>60, 'cat'=>'Watches & Accessories', 'img'=>'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600'],
            ['name'=>'Laptop Backpack 15.6" Anti-Theft','desc'=>'TSA-lock backpack with USB charging port, anti-theft zipper, 30L capacity and rain cover for 15.6" laptops.',                              'price'=>5999,   'qty'=>45, 'cat'=>'Watches & Accessories', 'img'=>'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'],
            ['name'=>'Women\'s Chain Necklace Gold',  'desc'=>'18K gold-plated stainless steel layered chain necklace. Tarnish-resistant, adjustable length 40-45cm.',                                       'price'=>1999,   'qty'=>90, 'cat'=>'Watches & Accessories', 'img'=>'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600'],
            ['name'=>'Passport Holder Travel Wallet', 'desc'=>'RFID-blocking travel wallet in PU leather holds passport, cards, boarding passes and SIM card tool.',                                         'price'=>1499,   'qty'=>110,'cat'=>'Watches & Accessories', 'img'=>'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=600'],
            ['name'=>'Baseball Cap Premium',          'desc'=>'Unstructured 6-panel cap in 100% cotton twill with curved brim, embroidered logo and adjustable strapback.',                                  'price'=>1299,   'qty'=>130,'cat'=>'Watches & Accessories', 'img'=>'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600'],

            // ── Food & Groceries (8) ──────────────────────────────────────
            ['name'=>'Premium Green Tea 250g',        'desc'=>'Single-origin Japanese Sencha green tea, first flush harvest. Rich in antioxidants with a smooth, grassy flavour.',                           'price'=>1799,   'qty'=>100,'cat'=>'Food & Groceries',    'img'=>'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600'],
            ['name'=>'Dark Chocolate Box 500g',       'desc'=>'Artisan 70% cocoa dark chocolate from Ecuador single-origin beans. 24 pieces with assorted flavoured fillings.',                              'price'=>3499,   'qty'=>60, 'cat'=>'Food & Groceries',    'img'=>'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600'],
            ['name'=>'Organic Honey Raw 1kg',         'desc'=>'Pure unfiltered raw honey from mountain wildflowers. No additives, cold-pressed, certified organic. 1kg glass jar.',                         'price'=>2999,   'qty'=>75, 'cat'=>'Food & Groceries',    'img'=>'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600'],
            ['name'=>'Protein Powder Whey 2kg',       'desc'=>'25g protein per serving, low sugar, instantised for easy mixing. Available in chocolate, vanilla and strawberry.',                            'price'=>7999,   'qty'=>50, 'cat'=>'Food & Groceries',    'img'=>'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600'],
            ['name'=>'Dried Fruit & Nuts Mix 1kg',    'desc'=>'Premium mix of cashews, almonds, walnuts, dried apricots, cranberries and dates. No added sugar or preservatives.',                          'price'=>4999,   'qty'=>80, 'cat'=>'Food & Groceries',    'img'=>'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600'],
            ['name'=>'Extra Virgin Olive Oil 1L',     'desc'=>'Cold-pressed EVOO from Spanish Arbequina olives. Acidity under 0.3%. Rich, fruity flavour for cooking and dressings.',                       'price'=>3999,   'qty'=>55, 'cat'=>'Food & Groceries',    'img'=>'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600'],
            ['name'=>'Instant Ramen Variety Pack 30s','desc'=>'30-pack variety box with 6 flavours from 3 countries. Authentic recipe, premium noodles and rich broth sachets.',                            'price'=>2499,   'qty'=>90, 'cat'=>'Food & Groceries',    'img'=>'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600'],
            ['name'=>'Coffee Beans Specialty 500g',   'desc'=>'Single-origin Ethiopian Yirgacheffe medium-roast whole beans. Tasting notes: blueberry, jasmine, dark chocolate.',                           'price'=>3299,   'qty'=>65, 'cat'=>'Food & Groceries',    'img'=>'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600'],
        ];

        foreach ($products as $p) {
            $catId = $cats->get($p['cat']);
            $product = Product::create([
                'name'        => $p['name'],
                'description' => $p['desc'],
                'price'       => $p['price'],
                'quantity'    => $p['qty'],
                'image_url'   => $p['img'],
                'image_path'  => null,
            ]);
            if ($catId) {
                $product->categories()->attach($catId);
            }
        }
    }
}
